# Generated by Django 3.1.2 on 2020-10-26 01:57

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text='Enter a Valid Email', max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(help_text='Password must be unique not contain only numbers', max_length=100, validators=[account.validators.MinimumLengthValidator, account.validators.NumberValidator, account.validators.UppercaseValidator], verbose_name='password'),
        ),
    ]
