# Generated by Django 3.1.2 on 2020-10-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201025_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(help_text='Password must be unique not contain only numbers', max_length=100, verbose_name='password'),
        ),
    ]
